# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Fredokun
tagline:          Outputs
url:              http://fredokun.github.io/
paginate:         1
baseurl:          /
author:
  name:           Frederic Peschanski
  url:            http://lip6.fr/Frederic/Peschanski
  email:          Frederic.Peschanski.work@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/fredokun/fredokun.github.io.git
